#!/bin/bash
#SBATCH --job-name=rand_stranet_entropy
#SBATCH --output=rand_stranetentropy_%j.out
#SBATCH --error=rand_stranetentropy_%j.err
#SBATCH --time=02:00:00
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=8G

module load fsl  # Load FSL if your system uses modules

randomise -i /foundcog/forrestgump/foundcog-infants-2m/resmem_model/second_level/merged_beta_maps/merged_resmem-prediction_4d.nii.gz \
          -o /foundcog/forrestgump/foundcog-infants-2m/resmem_model/second_level/results/oneSam_Resmem_Resmem_Model \
          -1 -T
